sudo: required

services:
  - docker 

before_install:
  - docker build -t dimwell/docker-react -f Dockerfile.dev .

script:
  - docker run dimwell/docker-react npm run test -- --coverage

# deploy:
  # providerr:    elasticbeanstalk
  # region:       "us-wes-2"  
  # app:          docker-react
  # env:          "Docker-env"
  # bucket_name:  "elasticbeanstalk-us-wes-2-306479XXXXXX"
  # bucket_path:  "docker-react"
  # on:
    # branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
    # secure: "$AWS_SECRET_KEY"